# how to use this file
# 1. make a copy of this file
# 2. have a parallel project
#   /path/to/this_project
#   /path/to/parallel_project
# 3. place the copy in parallel_project/setting
# 4. list the elements to be received
#   note that a full list can be found in setting.settings
# 5. run ./this_project/devel/deploy_links.py
# 6. soft links for each item in list will be created
receive:
  [
  common names,
  common paths,
  configure paths,
  configure settings,
  constant,
  data path,
  devel clean up,
  devel flags,
  log path,
  script initialize,
  setting paths,
  tool data management
  ]
