# global path keys
global_ = 'global'
run = 'run'
project = 'project'
projects = 'projects'
home = 'home'
desktop = 'Desktop'
documents = 'Documents'
downloads = 'Downloads'
music = 'Music'
pictures = 'Pictures'
videos = 'Videos'
# project path keys
# project = 'project'  # intentionally commented
configure = 'configure'
constant = 'constant'
data = 'data'
logs = 'logs'
script = 'script'
setting = 'setting'
# file path keys
file = 'file'
json_file = 'json cache'
logger_output = 'logger output'
yaml_logger_config = 'yaml logger config'
