# directories
dir_configure = 'configure'
dir_constant = 'constant'
dir_data = 'data'
dir_desktop = 'Desktop'
dir_documents = 'Documents'
dir_downloads = 'Downloads'
dir_logs = 'logs'
dir_music = 'Music'
dir_pictures = 'Pictures'
dir_script = 'script'
dir_setting = 'setting'
dir_videos = 'Videos'
# files
fn_json = 'cache.json'
fn_logger_config = 'logger.yaml'
fn_logger_output = 'event.log'
